version: '3.3'
services:
  tyk-dashboard:
    image: tykio/tyk-dashboard:v1.7.1
    ports:
    - "3000:3000"
    - "5000:5000"
    networks:
    - tyk
    depends_on:
    - tyk-redis
    - tyk-mongo
  tyk-gateway:
    image: tykio/tyk-gateway:v2.7.1
    ports:
    - "8080:8080"
    networks:
    - tyk
    depends_on:
    - tyk-redis
  tyk-pump:
    image: tykio/tyk-pump-docker-pub:v0.5.3
    networks:
    - tyk
    depends_on:
    - tyk-redis
    - tyk-mongo
    - tyk-gateway
  tyk-redis:
    image: redis
    ports:
    - "6379:6379"
    volumes:
    - redis-data:/data
    networks:
    - tyk
  tyk-mongo:
    image: mongo:3.2
    command: ["mongod", "--smallfiles"]
    ports:
    - "27017:27017"
    volumes:
    - mongo-data:/data/db
    networks:
    - tyk
  keycloak:
    image: c3genomics/keycloak:0.1
    ports: 
    - "9990:9990"
    - "9993:9993"
    - "8009:8009"
    - "8081:8080"
    - "8443:8443"
    - "4712:4712"
    - "4713:4713"
    networks:
    - tyk
  server:
    image: c3genomics/ga4gh_flask:0.2
    #command: ["--host", "0.0.0.0", "--port", "80", "--workers", "2"]
    ports:
    - "80:80"
    networks:
    - tyk

volumes:
  redis-data:
  mongo-data:

networks:
  tyk:
